### PR TITLE
fix astro workspace user add

### PR DESCRIPTION
**Pull request by andriisoldatenko**
Before change:
```
astro workspace user add andrii+1@astronomer.io --role=WORKSPACE_VIEWER
Error: API error (400): {"errors":[{"message":"Variable \"$role\" got invalid value \"viewer\"; Expected type Role.","locations":[{"line":2,"column":66}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

After change:
```
$ workspace user add andrii+1@astronomer.io --role=WORKSPACE_VIEWER --workspace-id=ck8c9lxy42d6a0968n2waller
 NAME              WORKSPACE ID                  EMAIL                      ROLE
 Astro Demo WS     ck8c9lxy42d6a0968n2waller     andrii+1@astronomer.io     WORKSPACE_VIEWER
Successfully added andrii+1@astronomer.io to Astro Demo WS
```

P.S. it was typo.

### CODE REVIEW

**Comment by vishwas-astro** [comment]
Can we add test(s) for this?

**Comment by vishwas-astro** [comment]
Also, @andriisoldatenko didn't remove have the same issue?

**Comment by kushalmalani** [comment]
Do we need to do the same for "workspaceUserUpdate"

**Comment by andriisoldatenko** [comment]
@kushalmalani nice catch
@vishwas-astro nope, only add/update.

**Pull request merged**
