### PR TITLE
Improve command help text

### PR DESCRIPTION
**Pull request by ryw**
Will continue to improve this text, but wanted to at least normalize capitalization and consolidate verbiage. We should review with @astrorfox to develop an official glossary of platform terms.

### CODE REVIEW

**Review by schnie — APPROVED** [review]
Nice! Agree on defining a glossary of terms to help define the product ASAP.

**Comment by astrorfox** [comment]
For the glossary, are you referring to consistent definitions around clusters, deployments, etc?

**Comment by schnie** [comment]
Exactly. I don't think we've quite nailed down everything, and the things we do have nailed down now, _could_ change in AEO/AstroHub world, if we wanted to.

Once we have the glossary defined, we can spread it around so we all speak the same language.

Another thing is also to simply define the relationship between a few things. For instance _right now_ there is an implicit relationship between an astro "project" and astro "deployments". That relationship is one to many. One project (DAG source code and scaffolding) can be pushed to many deployments in the remote "[kubernetes] cluster".

I don't know if we've ever documented this structure officially. Some of those relationships may change, and we may want to revisit the words we use here. @astrorfox interested to hear if you have any thoughts. Would be nice to have some of the core glossary nailed down as we start building the data model.

**Comment by ryw** [comment]
Yes a lot of this nomenclature is still informal - let's formalize in new product.

**Comment by astrorfox** [comment]
@jwitz is going to start a glossary in our style guide. TBD on whether we'll be able to harvest cleanly proper nouns from our current docs to prime it, but otherwise we'll crowdsource.

**Pull request merged**
