### PR TITLE
Fix message after astro deployment create new-deployment

### PR DESCRIPTION
**Pull request by andriisoldatenko**
fix astronomer/issues#459

### CODE REVIEW

**Comment by schnie** [comment]
They should be available through `Deployment.deployInfo` I think.

**Comment by andriisoldatenko** [comment]
practical test together with https://github.com/astronomer/houston-api/pull/211
```
$ astro deployment create new-deployment-name558 --executor=celery
Type 'help' for list of commands.
(dlv) c
 NAME     DEPLOYMENT NAME     ASTRO     DEPLOYMENT ID     TAG

 Successfully created deployment with Celery executor. Deployment can be accessed at the following URLs

 Airflow Dashboard: https://deployments.local.astronomer.io/false-instrument-4837/airflow
 Flower Dashboard: https://deployments.local.astronomer.io/false-instrument-4837/flower
```

**Comment by andriisoldatenko** [comment]
@schnie looks like we can merge it without waiting for another PRs.

**Comment by schnie** [comment]
LGTM!

**Pull request merged**
