### PR TITLE
Add success message after pushing all layers

### PR DESCRIPTION
**Pull request by andriisoldatenko**
fix https://github.com/astronomer/astro-cli/issues/210

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@paolaperaza @schnie pls review

**Comment by schnie** [comment]
I know we're nitpicking here but maybe just `Deploy succeeded!`

**Comment by paolaperaza** [comment]
Just left comment in issue but agreed with @schnie!

**Comment by andriisoldatenko** [comment]
@schnie fixed.

**Comment by schnie** [comment]
Nice!

**Pull request merged**
