### PR TITLE
Use Constant Instead of String

### PR DESCRIPTION
**Pull request by adam2k**
## Description

The `DEPLOYMENT_VIEWER` hard coded string value can be replaced with the constant value.

## 🎟 Issue(s)

Resolves astronomer/issues#1763

## 🧪 Functional Testing

The steps are the same as the original PR: https://github.com/astronomer/astro-cli/pull/365

## 📸 Screenshots

See https://github.com/astronomer/astro-cli/pull/365

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `make test` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Houston-API](https://github.com/astronomer/houston-api/) and [Astronomer](https://github.com/astronomer/astronomer/) (if necessary).
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@adam2k pls resolve conflicts.

**Review by andriisoldatenko — CHANGES_REQUESTED** [review]
LGTM, please resolve conflicts.

**Comment by adam2k** [comment]
> LGTM, please resolve conflicts.

It's updated now.

**Comment by adam2k** [comment]
@andriisoldatenko oops...it looks like these changes were already merged from the `deployment user delete` PR.  I can update the title of this because this is actually a different change (to use the constant instead of hard coded values).

**Review by andriisoldatenko — APPROVED** [review]

**Pull request merged**
