### PR TITLE
Include active hibernation override info in deployment metadata

### PR DESCRIPTION
**Pull request by feluelle**
## Description

> Describe the purpose of this pull request.

## 🎟 Issue(s)

closes: #1575 

## 🧪 Functional Testing

> List the functional testing steps to confirm this feature or fix.

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

For a deployment with override defined:
```
❯ ./astro deployment inspect cltwui4j6009401nwoqev94g7
deployment:
    configuration:
        name: create hosted dedicated
        description: desc
        runtime_version: 10.5.0
        dag_deploy_enabled: true
        ci_cd_enforcement: false
        scheduler_size: SMALL
        is_high_availability: false
        is_development_mode: true
        executor: CELERY
        scheduler_count: 1
        cluster_name: Sample AWS Cluster
        workspace_name: Sample Workspace 1
        deployment_type: DEDICATED
        cloud_provider: AWS
        region: ap-northeast-1
        default_task_pod_cpu: "0.25"
        default_task_pod_memory: 0.5Gi
        resource_quota_cpu: "2"
        resource_quota_memory: 4Gi
        workload_identity: ""
    worker_queues:
        - name: default
          max_worker_count: 4
          min_worker_count: 0
          worker_concurrency: 6
          worker_type: A10
    metadata:
        deployment_id: cltwui4j6009401nwoqev94g7
        workspace_id: cltwu72pz0198f7hgnnal41us
        cluster_id: cltwu71tx0004eehg6gnt39pc
        release_name: N/A
        airflow_version: 2.8.3
        current_tag: 10.5.0
        status: CREATING
        created_at: 2024-03-18T11:11:25.634Z
        updated_at: 2024-03-18T11:12:48.325Z
        deployment_url: cloud.astronomer-dev.io/cltwu72pz0198f7hgnnal41us/deployments/cltwui4j6009401nwoqev94g7/overview
        webserver_url: sampleorgpr19854-pr19854.astronomer-dev.run/dqev94g7?orgId=org_LL0XyTELYJS9ZOE0
        hibernation_override:
            is_hibernating: true
            override_until: 2100-01-01T00:00:00Z
```
For a deployment without override defined:
```
❯ ./astro deployment inspect cltwui4j6009401nwoqev94g7
deployment:
    configuration:
        name: create hosted dedicated
        description: desc
        runtime_version: 10.5.0
        dag_deploy_enabled: true
        ci_cd_enforcement: false
        scheduler_size: SMALL
        is_high_availability: false
        is_development_mode: true
        executor: CELERY
        scheduler_count: 1
        cluster_name: Sample AWS Cluster
        workspace_name: Sample Workspace 1
        deployment_type: DEDICATED
        cloud_provider: AWS
        region: ap-northeast-1
        default_task_pod_cpu: "0.25"
        default_task_pod_memory: 0.5Gi
        resource_quota_cpu: "2"
        resource_quota_memory: 4Gi
        workload_identity: ""
    worker_queues:
        - name: default
          max_worker_count: 4
          min_worker_count: 0
          worker_concurrency: 6
          worker_type: A10
    metadata:
        deployment_id: cltwui4j6009401nwoqev94g7
        workspace_id: cltwu72pz0198f7hgnnal41us
        cluster_id: cltwu71tx0004eehg6gnt39pc
        release_name: N/A
        airflow_version: 2.8.3
        current_tag: 10.5.0
        status: CREATING
        created_at: 2024-03-18T11:11:25.634Z
        updated_at: 2024-03-18T11:28:25.717Z
        deployment_url: cloud.astronomer-dev.io/cltwu72pz0198f7hgnnal41us/deployments/cltwui4j6009401nwoqev94g7/overview
        webserver_url: sampleorgpr19854-pr19854.astronomer-dev.run/dqev94g7?orgId=org_LL0XyTELYJS9ZOE0
```

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `make test` before taking out of draft
- [x] Ran `make lint` before taking out of draft
- [x] Added/updated applicable tests
- [ ] Tested against [Astro-API](https://github.com/astronomer/astro/) (if necessary).
- [ ] Tested against [Houston-API](https://github.com/astronomer/houston-api/) and [Astronomer](https://github.com/astronomer/astronomer/) (if necessary).
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

**Review by vandyliu — APPROVED** [review]

**Review by kushalmalani — APPROVED** [review]
LGTM

**Comment by kushalmalani** [comment]
@feluelle Is this good to merge?

**Comment by feluelle** [comment]
I will manually test this to be sure.

**Comment by feluelle** [comment]
I have found an issue on the core platform API side which holds me back from e2e testing it. The `isHibernating` field is missing from deployment response hibernation override field in platform API for some reason. I will look into that on Monday.

**Comment by feluelle** [comment]
Works as expected. I have added the tests to the PR description. @kushalmalani feel free to merge.

**Pull request merged**
