### PR TITLE
add airflow upgradedb

### PR DESCRIPTION
**Pull request by andriisoldatenko**

### CODE REVIEW

**Comment by schnie** [comment]
@andriisoldatenko nice fix. Does this work in practice consistently? I'm wondering what would happen if the webserver boots up first and there is no schema.

Should we just add it on both webserver / scheduler to be safe? It'd be closer to the previous behavior I guess.

**Comment by andriisoldatenko** [comment]
@schnie webserver depends on `scheduler.`
```
  webserver:
    image: {{ .AirflowImage }}
    command: >
      bash -c "airflow create_user -r Admin -u admin -e admin@example.com -f admin -l user -p admin && airflow webserver"
    restart: unless-stopped
    networks:
      - airflow
    user: {{ .AirflowUser }}
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-webserver"
    depends_on:
      - scheduler
      - postgres
```

**Comment by andriisoldatenko** [comment]
or do you mean this:
>depends_on does not wait for db and redis to be “ready” before starting web - only until they have been started. If you need to wait for a service to be ready, see Controlling startup order for more on this problem and strategies for solving it.

**Comment by schnie** [comment]
Oh that might be good then!

**Pull request merged**
