### PR TITLE
moved include package logic into airflow.go

### PR DESCRIPTION
**Pull request by nitinmewar**
Signed-off-by: nitinmewar <nitinmewar28@gmail.com>

## Description

moved python code to separate files instead of static go string. I am using embed to copy python file's content into variable.

## 🎟 Issue(s)

Related #XXX

#664

### CODE REVIEW

**Comment by nitinmewar** [comment]
@neel-astro how can I resolve these merge conflict.

**Review by neel-astro — APPROVED** [review]
LGTM, I have resolved the merge conflicts. But I think we would need to ignore the `airflow/include/composeyml.yml` in `.yamllint` configuration file. Reference: https://github.com/astronomer/astro-cli/blob/main/.yamllint#L5-L6

Ignore field after the change might look like:
```
ignore: |
  vendor
  airflow/include/composeyml.yml
```

**Comment by nitinmewar** [comment]
@neel-astro what now?

**Review by neel-astro — APPROVED** [review]

**Comment by nitinmewar** [comment]
thanks!! @neel-astro

**Review by sunkickr — APPROVED** [review]
LGTM

**Pull request merged**
