### PR TITLE
Add AUR package to docs.

### PR DESCRIPTION
**Pull request by mijoharas**
## Description
I added an aur package for installing astro-cli [here](https://aur.archlinux.org/packages/astro-cli/). I'm happy to pass ownership of this over to you if you'd like.

I'm not a fan of curl into sudo bash, and this allows the package to be managed by a package manager.

The full PKGBUILD is available here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=astro-cli .

## 📋 Checklist

- [ ] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `make test` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Houston-API](https://github.com/astronomer/houston-api/) and [Astronomer](https://github.com/astronomer/astronomer/) (if necessary).
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [x] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
LGTM, let's update version to [1.0.0](https://github.com/astronomer/astro-cli/releases/tag/v1.0.0) and we can merge this.

**Comment by mijoharas** [comment]
Updated. Let me know if anyone from the astronomer team wants me to transfer ownership of the pkgbuild over to them at any point.

**Comment by andriisoldatenko** [comment]
@mijoharas please coordinate with @neel-astro

**Comment by sunkickr** [comment]
@mijoharas for now we have decided as a team to focus our efforts on maintaining other linux package. We will reach back out when we have the ability to also maintain aur. We have decided to not add the package to our README till we are able to maintain it

**Pull request closed without merging**
