### PR TITLE
hotfix: workspace user remove

### PR DESCRIPTION
**Pull request by andriisoldatenko**
```
astro-cli workspace user remove ckdj7pfxr00re0j0351fhhlcb
 NAME                          WORKSPACE ID                                      EMAIL
 Astro Demo WS                 ck8c9lxy42d6a0968n2waller                         ckdj7pfxr00re0j0351fhhlcb
Successfully removed user from workspace
```

depend on this very old PR https://github.com/astronomer/houston-api/pull/74/files

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@adam2k yep on it.

**Comment by andriisoldatenko** [comment]
@adam2k PTAL

**Comment by andriisoldatenko** [comment]
@kushalmalani we are trying to get rid of `Uuid` prefix AFAIK.

**Comment by andriisoldatenko** [comment]
@kushalmalani JFYI https://github.com/astronomer/astro-cli/commit/f0e0ba338ada2a7f4c83c8951e252e517a9591f9

**Comment by schnie** [comment]
UUID terminology can be removed in favor of just the ID. It's just legacy stuff from Houston 1. Should be converting everything

**Pull request merged**
