### PR TITLE
Update dagintegritytestdefault.py

### PR DESCRIPTION
**Pull request by dylanbstorey**
## Description

>Updates the os.getenv monkey patch to manage people who are setting defaults with args instead of kwargs

## 🎟 Issue(s)

Its come up with CRE/Field where customers are using the valid but less explicit `os.getenv(key,default)` in their code and our monkey patch wasn't honoring their default. This SHOULD address both `os.getenv(key,default)` and `os.getenv(key,default=value` patterns that are valid. 

## 🧪 Functional Testing

> List the functional testing steps to confirm this feature or fix.
put a few `os.getenv()` statements in the top of a dag and did some echo debugging

Screenshot 2023-02-24 094746

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.
Screenshot 2023-02-24 091721

## 📋 Checklist

- [ ] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `make test` before taking out of draft
- [ ] Ran `make lint` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Astro-API](https://github.com/astronomer/astro/) (if necessary).
- [ ] Tested against [Houston-API](https://github.com/astronomer/houston-api/) and [Astronomer](https://github.com/astronomer/astronomer/) (if necessary).
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

**Comment by collinmcnulty** [comment]
Why is there a None between x and that in the echo?

**Comment by dylanbstorey** [comment]
the first prints occur when the module is imported , but before the mocks are applied to the DagBag import

**Comment by dylanbstorey** [comment]
2 reasons - 

screen shot of the code wasn't correct. and the initial prints occur when the module is loaded by pytest. the next 2 are the 2 dagbag imports that occur and mocks are applied

**Review by ReadytoRocc — APPROVED** [review]
LGTM

**Review by sunkickr — APPROVED** [review]
I tested this out manually and it works fine

**Pull request merged**
