### PR TITLE
Restrict port exposure for local project to localhost

### PR DESCRIPTION
**Pull request by neel-astro**
## Description
Changes:
- Restrict the local project's port exposure to just 127.0.0.1, instead of allowing anyone in the network to access the webserver/Postgres port

## 🎟 Issue(s)

Related #685 

## 🧪 Functional Testing

> List the functional testing steps to confirm this feature or fix.

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `make test` before taking out of draft
- [x] Ran `make lint` before taking out of draft
- [x] Added/updated applicable tests
- [ ] Tested against [Astro-API](https://github.com/astronomer/astro/) (if necessary).
- [ ] Tested against [Houston-API](https://github.com/astronomer/houston-api/) and [Astronomer](https://github.com/astronomer/astronomer/) (if necessary).
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@neel-astro i think you should fix few tests.

**Review by andriisoldatenko — APPROVED** [review]
code LGTM, but please check CI.

**Comment by neel-astro** [comment]
> code LGTM, but please check CI.

looked like some tests were failing as Astro Dev environment was down for sometime yesterday, tests are working fine now

**Review by kushalmalani — APPROVED** [review]

**Comment by tehe** [comment]
FWIW, we just updated to astro CLI 1.11.0 where this change landed and it breaks our development setup, which is:

1. Run `astro dev start` on a remote server (in our case a VM in Azure where we connect over ssh)
2. Setup port 8080 forwarding from that remote machine to the laptop where we run a browser to access the Airflow UI

But because of this change, the web server will only listen on the localhost/127.0.0.1 and the port forwarding will not work.

**Comment by neel-astro** [comment]
We are already aware of this issue and are working on a fix/workaround. We will try to land the fix in the next release.

**Pull request merged**
