### PR TITLE
add ability to manually set releaseName during create deployment

### PR DESCRIPTION
**Pull request by andriisoldatenko**
fix astronomer/issues#548

related PR https://github.com/astronomer/houston-api/pull/266

### CODE REVIEW

**Comment by schnie** [comment]
@andriisoldatenko this is going to be a platform level setting - if you can set this releaseName or not. It's going to come down in the `appConfig` query now. Do we need to adjust this to deal with if this functionality is enabled or not?

**Comment by andriisoldatenko** [comment]
@schnie good catch, i'll fix my pr according latest Sam's changes in houston-api.

**Comment by andriisoldatenko** [comment]
@schnie PTAL

**Comment by andriisoldatenko** [comment]
practically LGTM:
```
astro deployment create new-deployment-name --executor=celery --release-name=hello-from-astro-cli
 NAME                    DEPLOYMENT NAME          ASTRO              DEPLOYMENT ID                 TAG
 new-deployment-name     hello-from-astro-cli     0.13.0-alpha.2     ck9ukag1a01w70j740sibbxkp     %!s(MISSING)
 Successfully created deployment with Celery executor. Deployment can be accessed at the following URLs
 Airflow Dashboard: https://deployments.local.astronomer-development.com/hello-from-astro-cli/airflow
 Flower Dashboard: https://deployments.local.astronomer-development.com/hello-from-astro-cli/flower
2:47
NAME                                              READY   STATUS     RESTARTS   AGE
hello-from-astro-cli-flower-769559c7b5-2qw95      1/1     Running    0          54s
hello-from-astro-cli-pgbouncer-5cdf8dc6f4-dql8p   2/2     Running    0          54s
hello-from-astro-cli-redis-0                      1/1     Running    0          54s
hello-from-astro-cli-scheduler-77b69646d6-7lmds   0/2     Init:0/1   0          54s
hello-from-astro-cli-statsd-f4579cdfb-l4jrn       1/1     Running    0          54s
hello-from-astro-cli-webserver-6d5867df75-sws5n   0/1     Init:0/1   0          54s
hello-from-astro-cli-worker-676c4f97b9-fxkfc      0/1     Init:0/1   0          54s
2:48
astro deployment create new-deployment-name1 --executor=celery --release-name=hello_test_fail
Error: Release name not formatted correctly.
exit status 1
LGTM

**Pull request merged**
