### PR TITLE
Remove tags & retries tests since they're not applicable to most projects

### PR DESCRIPTION
**Pull request by BasPH**
Removing the pytest cases testing for DAG tags & retries, following discussion in https://astronomer.slack.com/archives/CL44PA4DB/p1680001384869019.

Most customers don't have tags & retries configured on all DAGs so I don't think we should enforce that via tests.

## Description

> Describe the purpose of this pull request.

## 🎟 Issue(s)

- https://github.com/astronomer/astro-cli/issues/1115

## 🧪 Functional Testing

Tested change by doing a fresh `astro dev init` and running `astro dev pytest` successfully.

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

## 📋 Checklist

- [ ] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `make test` before taking out of draft
- [ ] Ran `make lint` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Astro-API](https://github.com/astronomer/astro/) (if necessary).
- [ ] Tested against [Houston-API](https://github.com/astronomer/houston-api/) and [Astronomer](https://github.com/astronomer/astronomer/) (if necessary).
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

**Comment by dylanbstorey** [comment]
I'm also in favor of this as its an opinionated style piece that is non obvious and not "generally" applicable. Maybe just comment them out and allow people to see what the tests look like and do what they will vs full deletion though ?

**Comment by BasPH** [comment]
I'd rather explain that in docs than having commented code, for example under https://docs.astronomer.io/astro/test-and-troubleshoot-locally#run-tests-with-pytest or https://docs.astronomer.io/astro/cli/astro-dev-pytest.

**Comment by dylanbstorey** [comment]
Should we open a matching issue with our docs page ?

**Comment by sunkickr** [comment]
@dylanbstorey @BasPH has a docs issues been opened yet?

**Comment by dylanbstorey** [comment]
A general issue was opened on this subject, not 100% sure where its at though.

**Review by dylanbstorey — APPROVED** [review]

**Comment by kushalmalani** [comment]
@BasPH Is this good to merge?

**Comment by erdos2n** [comment]
I've written a similar issue where we don't delete the pytest but we can skip them using a variable. The PyTest is helpful and from a reliability perspective helps customers with DAG integrity, but it should be configurable. 

Issue #1398

**Comment by erdos2n** [comment]
@BasPH  can we close this PR? This looks to be handled by PR #1404

**Pull request closed without merging**
