### PR TITLE
Backport "airflow_settings.yaml" and ".env" feature to 0.7

### PR DESCRIPTION
**Pull request by benjamingregory**
Backports some 0.8 features to 0.7:
- Add connections, variable, and pool creation via airflow_settings.yaml
- Add support for ".env" and other env files via `-e` flag

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@benjamingregory does it just cherry pick?

**Comment by andriisoldatenko** [comment]
Please squash commits and sync with master if needed.

**Comment by schnie** [comment]
@andriisoldatenko yea we have a customer on an old version, so we need to backport this feature to the 0.7 release branch so we can cut an 0.7.6 patch release. I think @benjamingregory cherry-picked these commits from master.

**Comment by schnie** [comment]
Also, I typically default to "Squash and merge" on github, so that will take care of the squash.

**Pull request merged**
