### PR TITLE
Remove update deployment sync flag

### PR DESCRIPTION
**Pull request by adam2k**
Remove deprecated sync flag from Update Deployment requests.

Fixes https://github.com/astronomer/issues/issues/1579

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
LGTM!

**Comment by vishwas-astro** [comment]
@schnie can you review this and merge please?

**Comment by andriisoldatenko** [comment]
@adam2k i think we need to remove it also from astro-cli!

**Comment by adam2k** [comment]
@andriisoldatenko Do you mean `astro-ui`?  @ryanahamilton created a PR that remove this from `astro-ui` already and there is a different PR for `houston-api`.  

See these two issues:
#1577
#1578

**Comment by andriisoldatenko** [comment]
@adam2k sorry my fault. nvm.

**Pull request merged**
