### PR TITLE
If Houston-API throws ErrAuthTokenRefreshFailed error, then show ErrVerboseInaptPermissions message in the cli

### PR DESCRIPTION
**Pull request by rujhan-arora-astronomer**
## Description

> Describe the purpose of this pull request.
If Houston-API throws ErrAuthTokenRefreshFailed error, then show ErrVerboseInaptPermissions message in the cli

## 🎟 Issue(s)

Related astronomer/issues#4341

## 🧪 Functional Testing

> List the functional testing steps to confirm this feature or fix.

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `make test` before taking out of draft
- [x] Added/updated applicable tests
- [ ] Tested against [Houston-API](https://github.com/astronomer/houston-api/) and [Astronomer](https://github.com/astronomer/astronomer/) (if necessary).
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

**Review by andriisoldatenko — APPROVED** [review]

**Comment by AmFlint** [comment]
Shouldn't we display a more more specific error message ? Something like "Access token has expired, you need to log in again." is clearer than "Inappropriate permissions"

**Comment by andriisoldatenko** [comment]
> Shouldn't we display a more more specific error message ? Something like "Access token has expired, you need to log in again." is clearer than "Inappropriate permissions"

+1

☝️

**Comment by rujhan-arora-astronomer** [comment]
> Shouldn't we display a more more specific error message ? Something like "Access token has expired, you need to log in again." is clearer than "Inappropriate permissions"

Even presently, we show ErrVerboseInaptPermissions if a user is using the expired token to use CLI. So keeping it consistent with the current message. Also, Auth Token Refresh is an encapsulated implementation and customers don't specifically need to know that their token refresh failed.  @aliotta  Please correct me if I am wrong somewhere.

**Comment by vishwas-astro** [comment]
> Shouldn't we display a more more specific error message ? Something like "Access token has expired, you need to log in again." is clearer than "Inappropriate permissions"

I am not sure about divulging the reasons for an invalid authentication/authorization. Usually keeping it high level such as invalid credentials or session expired is better

**Review by AmFlint — APPROVED** [review]
Can we merge this PR please ?

**Comment by rujhan-arora-astronomer** [comment]
> Can we merge this PR please ?

@andriisoldatenko @neel-astro

**Review by neel-astro — APPROVED** [review]

**Pull request merged**
